const hobbies = ['Sleeping','Eating','Playing','Coding','Roaming']
const isArrayorNot = Array.isArray(hobbies)
console.log(isArrayorNot)
const hasCricket = hobbies.includes ('Cricket');
console.log(hasCricket)
hobbies.push('Guitar','Valleyball')
console.log(hobbies)
hobbies.pop()
console.log(hobbies)
hobbies.unshift('Numismatics','Singing')
console.log(hobbies)
hobbies.shift()
console.log(hobbies)
const hobbies1 = ['Sleeping','Cricket','Eating','Coding'];
hobbies1.splice(1,2,'Bird Flying','Pubg')
console.log(hobbies1)
const afterSlice = hobbies1.slice(2,4)
console.log(hobbies1)
console.log(afterSlice)
const indexOfCoding = hobbies1.indexOf('Coding',1)
console.log(indexOfCoding);
const stringHobbies = hobbies1.join('-')
console.log(stringHobbies)
const books = ['Abc','Bcd','Cde','Def']
const books1 = Array.isArray(books)
console.log(books1)
const xyz = books.includes('xyz')
console.log(xyz)
books.push('Cad','Ghf')
console.log(books)
books.pop()
console.log(books)
books.unshift('Ahf','Vab')
console.log(books)
books.shift()
console.log(books)
const books2 = ['acd','def','sdh','fgh'];
books2.splice(1,2,'dhn','hbn')
console.log(books2)
const books3=books2.slice(2,4)
console.log(books2)
console.log(books3)
const books4 = books2.join('-')
console.log(books4)
const pens = ['Bright','Renals','Cello Faster','Boll']
const pens1 = Array.isArray(pens)
console.log(pens1)
const pens2 = pens.includes('Bright')
console.log(pens2)
pens.push('flay','Gell')
console.log(pens)
pens.pop()
console.log(pens) 
pens.unshift('grac','hali')
console.log(pens)
pens.shift()
console.log(pens)
const pens3 = ['acd','def','sdh','fgh'];
pens3.splice(1,2,'dhn','hbn')
console.log(pens3)
const pens4=pens3.slice(2,4)
console.log(pens3)
console.log(pens4)
const pens5= pens4.join('-')
console.log(pens4)
const sports = ['coco','Basket Boll','Table Tenis','Cricket']
const sports1 = Array.isArray(sports)
console.log(sports1)
const sports2= sports.includes('coco')
console.log(sports2)
sports.push('bating','oliboll')
console.log(sports)
sports.pop()
console.log(sports)
sports.unshift('killa','kabadi')
console.log(sports)
sports.shift()
console.log(sports)
const sports3 = ['coco','bolling','tenis','killa']
sports3.splice(1,2,'cricket','carams')
console.log(sports3)
const sports4=sports3.slice(2,4)
console.log(sports3)
console.log(sports4)
const sports5 = sports4.join('-')
console.log(sports5)
const food = ['Rice','curry','chpathi']
const food1 = Array.isArray(food)
console.log(food1)
const food2 = food.includes('Rice')
console.log(food2)
food.push('Cicken','mutton')
console.log(food)
food.pop()
console.log(food)
food.unshift('fish','pronce')
console.log(food)
food.shift()
console.log(food)
const food3 = ['biryani','kurma','rasam','idly'];
food3.splice(1,2,'pulihora','upittu')
console.log(food3)
const food4=food3.slice(2,4)
console.log(food3)
console.log(food4)
const food5= food3.join('-')
console.log(food5)
const clothes = ['Jeans','Tops','Kurthis']
const clothes1 = Array.isArray(clothes)
console.log(clothes1)
const clothes2 = clothes.includes('Jeans')
console.log(clothes2)
clothes.push('shirt','pant')
console.log(clothes)
clothes.pop()
console.log(clothes)
clothes.unshift('sweter','braser')
console.log(clothes)
clothes.shift()
console.log(clothes)
const clothes3 = ['shirt','pant','teashirt','jeen'];
clothes3.splice(1,2,'denim','saree')
console.log(clothes3)
const clothes4=clothes3.slice(2,4)
console.log(clothes3)
console.log(clothes4)
const clothes5 = clothes3.join('-')
console.log(clothes5)
const bikes = ['Hero Honda','Duke','Royal Enfeeld']
const bikes1 = Array.isArray(bikes)
console.log(bikes1)
const bikes2 = bikes.includes('Duke')
console.log(bikes2)
bikes.push('kklm','fgyh')
console.log(bikes)
bikes.pop()
console.log(bikes)
bikes.unshift('ferari','Vamika')
console.log(bikes)
bikes.shift()
console.log(bikes)
const bikes3 = ['acd','def','sdh','fgh'];
bikes3.splice(1,2,'dhn','hbn')
console.log(bikes3)
const bikes4=bikes3.slice(2,4)
console.log(bikes3)
console.log(bikes4)
const bikes5 = bikes3.join('-')
console.log(bikes5)
const mobiles = ['mi','redme','samsung','oppo','vivo']
const mobiles1 = Array.isArray(mobiles)
console.log(mobiles1)
const mobiles2 = mobiles.includes('redme')
console.log(mobiles2)
mobiles.push('sony','intex')
console.log(mobiles)
mobiles.pop()
console.log(mobiles)
mobiles.unshift('soni','moto')
console.log(mobiles)
mobiles.shift()
console.log(mobiles)
const mobiles3 = ['acd','def','sdh','fgh'];
mobiles3.splice(1,2,'dhn','hbn')
console.log(mobiles3)
const mobiles4=mobiles3.slice(2,4)
console.log(mobiles4)
console.log(mobiles4)
const mobiles5 = mobiles3.join('-')
console.log(mobiles5)
const watches = ['Fastrack','sonata','titan']
const watches1 = Array.isArray(watches)
console.log(watches1)
const watches2 = watches.includes('titan')
console.log(watches2)
watches.push('rolex','cinic')
console.log(watches)
watches.pop()
console.log(watches)
watches.unshift('tink','spring')
console.log(watches)
watches.shift()
console.log(watches)
const watches3 = ['mi','titan','fastrack','rolex'];
watches3.splice(1,2,'dhn','hbn')
console.log(watches3)
const watches4=watches3.slice(2,4)
console.log(watches3)
console.log(watches4)
const watches5 = watches3.join('-')
console.log(watches5)
console.log('=====================')